
## Extract parameters

```{r}
rm(list = ls())
source("../analysis_funcs.R")

WD = '../../data'
WDD = file.path(WD, 'experiment')
mytheme = theme_classic(base_size = 13) + theme(legend.position = 'bottom', legend.title = element_blank() ) 
theme_set(mytheme)
# Load previous fit
MYFILE = '../results/linear_drift_ddm-02-05-2022_00:03-10000-50000-jags-pars.RData'
load(MYFILE)
numSubjs = dataList$N

# Load data
load(file.path(WDD, "processed_data_censored.RData"))
grouping_var = 'subj_context'
choicedata.common$subj_context = paste(choicedata.common$subjID, choicedata.common$context)
dataList = organize_data(choicedata.common, grouping_var, long = T)
subjList <- unique(choicedata.common[c('subjID', 'context', 'context_num', 'context_order', 'background_col', grouping_var)]) 

choicedata.common = choicedata.common %>% mutate(Context = ifelse(context == 'c1', 'High volatility', 'Low volatility'),
                                   Choice = ifelse(choice == 1, 'Later option', 'Immediate option'))

ratingdata.sub = ratingdata.sub %>% mutate(Context = ifelse(context == 'c1', 'High volatility', 'Low volatility'))

```


```{r}
## Extract parameters
numPars <- 5

# Individual parameters (e.g., individual posterior means)
allIndPars <- array(NA, c(numSubjs, numPars))
allIndPars <- as.data.frame(allIndPars)

for (i in 1:numSubjs) {
  allIndPars[i, ] <- c( 
  mean(parVals$b.drift.intercept.p[i, ]), 
  mean(parVals$b.drift.amount.p[i, ]), 
  mean(parVals$bias.p[i, ]), 
  mean(parVals$nondectime.p[i, ]), 
  mean(parVals$noise.p[i, ])
  )
}

allIndPars = cbind(allIndPars, subjList[-ncol(subjList)]) 

colnames(allIndPars) <- c(
"b.drift.intercept.p", 
"b.drift.amount.p", 
"bias.p", 
"nondectime.p", 
"noise.p", 
"subjID", "context", "context_num", "context_order", "background_col")

```
## Remove subjects if they have low sensitivity

```{r}

Rhat = max(myfit_summary[, 'psrf'])
print(Rhat)

g = grep( "b.drift.amount.p\\[", rownames(myfit_summary))
allIndPars$lower_bound = myfit_summary[g, 'Lower95']
allIndPars$upper_bound = myfit_summary[g, 'Upper95']
allIndPars$Median = myfit_summary[g, 'Median']
allIndPars$b.drift.amount.p.0 = allIndPars$lower_bound >0 | allIndPars$upper_bound < 0 

plot(allIndPars$lower_bound[order(allIndPars$lower_bound)], type = 'l', ylim = c(min(allIndPars$lower_bound), max(allIndPars$upper_bound)),
     xlab = "Subject/Context", ylab = "5%-quantile for drift sensitivity")
#lines(allIndPars$upper_bound[order(allIndPars$lower_bound)]  , type = 'l')
abline(0, 0, col = 'red')

```


```{r, fig.width = 15}
allIndPars$index = seq(nrow(allIndPars))

# keep subjects with a significant relationship between drift and value
allIndPars.subj = allIndPars %>% group_by(subjID) %>% summarise(keep = max(lower_bound) > 0) %>% filter(keep) %>% ungroup()
include_subjects = allIndPars.subj$subjID

allIndPars.sub = subset(allIndPars, subjID %in% include_subjects)

```

## Group distributions for parameters

```{r}

for (var in c("context",  "background_col"))
{
  get_par_jags("b.drift.intercept.p", var)
  get_par_jags("b.drift.amount.p", var)
  get_par_jags("bias.p", var )
  get_par_jags("nondectime.p", var)
  get_par_jags("noise.p", var)
}
context_sigmas = c(5, 2, 1)

allIndPars$context_sigma = context_sigmas[allIndPars$context_num]

mypars = c("b.drift.intercept.p", "b.drift.amount.p", "bias.p", "nondectime.p", "noise.p") 


for (mypar in mypars){
  print("------------------------------------")
  print(mypar)
  myform = formula(paste(mypar, "context + context_order + (1|subjID)", sep = "~"))
  model = lmer(myform, data = allIndPars %>% filter(subjID %in% include_subjects))
  print(summary(model))

} 
```



## Plot RTs in relation to estimated subjective value
```{r}
breaks = seq(0.5, 8.5, 1)
choicedata = merge(choicedata.common, allIndPars %>% filter(subjID %in% include_subjects), by = c('subjID', 'context', 'context_order', 'background_col'))
choicedata = choicedata %>% mutate( ev = amount_later, context_num = as.numeric(substr(context, 2, 2))) %>% mutate(ev.cut = cut(ev, breaks))

# outliers removed beforehand
choicedata.group = choicedata %>% 
  group_by(subjID, Context, ev.cut) %>% 
  dplyr::summarise(rt.median = median(rt), ev = mean(ev), prob_late = mean(choice))
choicedata.group = choicedata.group%>%
  group_by(Context, ev.cut) %>% 
  dplyr::summarise(rt.mean = mean(rt.median), rt.sem = sem(rt.median), 
            prob_late.mean = mean(prob_late), prob_late.sem = sem(prob_late),
            ev = mean(ev))

myplot.RT = ggplot(data = choicedata.group, aes(x = ev, y = rt.mean, ymin = rt.mean - rt.sem, ymax = rt.mean + rt.sem, color = Context, group = Context)) +
  geom_line() + 
  geom_point() + 
  geom_errorbar() + 
  xlab('Later amount') +
  ylab('RT (s)') 

print(myplot.RT)

choicedata.group.choice = choicedata %>% 
  group_by(subjID, Context, ev.cut, Choice) %>% 
  dplyr::summarise(rt.median = median(rt), ev = mean(ev), prob_late = mean(choice))

choicedata.group.choice = choicedata.group.choice%>%
  group_by(Context, ev.cut, Choice) %>% 
  dplyr::summarise(rt.mean = mean(rt.median), rt.sem = sem(rt.median), 
            prob_late.mean = mean(prob_late), prob_late.sem = sem(prob_late),
            ev = mean(ev))

# separate by choice
myplot.RT.choice = ggplot(data = choicedata.group.choice, aes(x = ev, y = rt.mean, ymin = rt.mean - rt.sem, ymax = rt.mean + rt.sem, color = Context, group = Context)) +
  geom_line() + 
  geom_point() + 
  geom_errorbar() + 
  xlab('Later amount') + 
  ylab('RT (s)') + facet_grid( .~Choice ) + theme(legend.position = 'bottom', legend.title = element_blank() ) 

print(myplot.RT.choice)

myplot = ggplot(data = choicedata, aes(x = cut(ev, breaks), y = log(rt), fill = context)) +
  geom_violin() + 
  xlab('Subjective value of later amount') + 
  ylab('RT (s)') + ylim(-5, 5)

#print(myplot)

choicedata$amount_later_centered.2 = choicedata$amount_later_centered^2  
model = lmer(log(rt) ~ context*(amount_later_centered + amount_later_centered.2)  + context_order + (1 + amount_later_centered|subjID), data = choicedata)
print(summary(model))

```



## Check probabilities

```{r}
myplot.choiceprob = ggplot(data = choicedata.group, aes(x = ev, y = prob_late.mean, ymin = prob_late.mean - prob_late.sem, 
                                             ymax = prob_late.mean + prob_late.sem, color = Context, ratinggroup = Context)) +
  geom_line() + 
  geom_point() + 
  geom_errorbar() + 
  xlab('Later amount') + 
  ylab('Probability of later option') + theme(legend.position = 'bottom', legend.title = element_blank() ) 

print(myplot.choiceprob)

model = glmer(choice ~ context*(amount_later_centered + amount_later_centered.2)  + context_order + (1 + amount_later_centered|subjID), data = choicedata, family = 'binomial' )
print(summary(model))
plot(model)
```






## Plot ratings in relation to estimated subjective value
```{r}
ratingdata.sub$bid.diff = ratingdata.sub$bid.high - ratingdata.sub$bid.low

ratingdata.sub$bid.rt.max = apply(ratingdata.sub[ c('bid.high.rt', 'bid.low.rt') ], 1, max)
ratingdata.sub$bid.rt.min = apply(ratingdata.sub[ c('bid.high.rt', 'bid.low.rt') ], 1, min)

ratingdata.sub = ratingdata.sub %>% 
  mutate(bid.rt.second = bid.rt.max - bid.rt.min,
         bid.rt.first = bid.rt.min)


#remove outliers
ratingdata.sub = ratingdata.sub %>% group_by(amount_later) %>% mutate(bid.diff.outlier = markoutliersIQR(log(bid.diff)),
                                                                      bid.rt.outlier = markoutliersIQR(log(bid.rt.max)))
ratingdata.sub.clean = subset(ratingdata.sub, bid.diff.outlier == F & bid.rt.outlier == F )


ratingdata = merge(ratingdata.sub.clean, allIndPars %>% filter(subjID %in% include_subjects), by = c('subjID', 'context', 'context_num', 'context_order', 'background_col'))
ratindata = subset(ratingdata, subjID %in% include_subjects)
ratingdata = ratingdata %>% mutate( ev = amount_later_centered, bid.diff = (bid.high - bid.low )) %>% mutate(ev2 = ev^2)

myplot = ggplot(data = ratingdata, aes(x = ev, y = bid.diff, color = context, group = subjID)) +
  geom_line() + 
  geom_point() + 
  xlab('Subjective value of later amount') + 
  ylab('Price range') + facet_grid(.~context)
print(myplot)

ratingdata.group = ratingdata %>% 
  group_by(Context, amount_later) %>% 
  summarise(bid.diff.mean = mean(bid.diff), bid.diff.sem = sem(bid.diff), ev = mean(ev))

myplot.range = ggplot(data = ratingdata.group, aes(x = ev, y = bid.diff.mean, ymin = bid.diff.mean - bid.diff.sem, ymax = bid.diff.mean + bid.diff.sem, color = Context)) +
  geom_line() + 
  geom_point() + 
  geom_errorbar() + 
  xlab('Subjective value of later amount') + 
  ylab('Price range')

print(myplot.range)

model.diff = lmer(bid.diff ~ context*amount_later_centered + context_order + (1 + amount_later_centered | subjID), 
             data = ratingdata )
print(summary(model.diff))

model.high = lmer(bid.high ~ context*amount_later_centered + context_order + (1 + amount_later_centered | subjID), 
             data = ratingdata)
print(summary(model.high))

model.low = lmer(bid.low ~ context*amount_later_centered + context_order + (1 + amount_later_centered | subjID), 
             data = ratingdata)
print(summary(model.low))

```

## Rating RT
```{r}
mypars.rt = c('key.rt', 'bid.rt.max', 'bid.rt.min', 
           'bid.rt.second', 'bid.rt.first')

ratingdata$amount_later_centered.2 = ratingdata$amount_later_centered^2  
cor.est = cor.p = NULL
for (mypar in mypars.rt){
  print("------------------------------------")
  print(mypar)
  myform = formula(paste(paste0('log(', mypar, ')'), "context*(amount_later_centered + amount_later_centered.2) + context_order + (1 + amount_later_centered | subjID)", sep = "~"))
  model.rt = lmer(myform, data = ratingdata) 
  print(myform)
  print(summary(model.rt))
  # Random slopes of rating RTs vs DDM parameters
  #RFX = ranef(model.rt)$subjID 
  #RFX$subjID = rownames(RFX)
  #RFX = merge(RFX, allIndPars, by = "subjID")
  #cor.est = cbind(cor.est, sapply(RFX[mypars], function(x) cor.test(x, RFX$amount_later_centered)$estimate ))
  #cor.p = cbind(cor.p, sapply(RFX[mypars], function(x) cor.test(x, RFX$amount_later_centered)$p.value))
}
#colnames(cor.est) = colnames(cor.p) = mypars.rt
myplot = ggplot(data = ratingdata, aes(x = context, y = bid.rt.second/1000, fill = context)) +
  geom_violin() + 
  xlab('Context') +
  ylab('RT') 
print(myplot)

myplot = ggplot(data = ratingdata, aes(x = as.factor( amount_later_centered), y = bid.rt.second/1000, fill = context)) +
  geom_boxplot() + 
  xlab('Amount') +
  ylab('RT') 
print(myplot)
```

## Random slopes of ratings vs DDM parameters

```{r}
main.mat = inter.mat = NULL

mypars.rating = c("bid.diff", "bid.high", "bid.low")
for (mypar.rating in mypars.rating){
for (mypar in mypars){
     myformula = as.formula(sprintf("%s ~ scale(%s)*context*amount_later_centered + context_order + (1 + amount_later_centered | subjID)", mypar.rating, mypar)) 
     model = lmer(myformula, data = ratingdata)
     ss = summary(model)
     #print(ss)
     
     ss.1 = coef(ss)[7, c("t value", "Pr(>|t|)")]
     ss.2 = coef(ss)[9, c("t value", "Pr(>|t|)")]
     main.mat = rbind(main.mat, c(mypar.rating, mypar, round(ss.1, 3)))
     inter.mat = rbind(inter.mat, c(mypar.rating, mypar, round(ss.2, 3)))
     
  } 
} 
main.mat = as.data.frame(main.mat)
inter.mat = as.data.frame(inter.mat)
colnames(main.mat) = colnames(main.mat) = c("rating_par", "choice_par", "t", "p")
View(main.mat)
View(inter.mat)


myplot.main.intercept = ggplot(ratingdata, aes(x = jitter(amount_later), y = b.drift.intercept.p, col = bid.diff )) + geom_point() + scale_color_viridis_c()
print(myplot.main.intercept)

myplot.main.amount = ggplot(ratingdata, aes(x = jitter(amount_later), y = b.drift.amount.p, col = bid.diff )) + geom_point() + scale_color_viridis_c()
print(myplot.main.amount)

```

## Check stability of parameters

```{r, fig.width = 15}
allIndPars = allIndPars %>% mutate(Context = ifelse(context == 'c1', 'High', 'Low'))

allIndPars.melt = melt(allIndPars %>% filter(subjID %in% include_subjects), id.vars = c("subjID", "Context", "context", "context_order"), variable.name = "parameter", value.name = "value") %>% filter(parameter %in% mypars) %>%mutate(value = as.numeric(value), parameter_label = par_labels[parameter])
myplot.reliab = ggplot(allIndPars.melt, aes(x = Context, y = value, group = subjID)) + geom_line(size = 0.4) + geom_point(size = 0.6) +
  ylab('Parameter value') + 
  xlab('Volatility') + 
  facet_wrap( .~ parameter_label, scales = "free", nrow = 1 )

print(myplot.reliab)
#myplot = ggplot(allIndPars.melt, aes(x = context, y = value, group = context )) + geom_violin() + facet_grid( context_order ~ parameter, scales = "free" )
#print(myplot)

allIndPars.melt$value.corr = 0
for ( mypar in mypars){
  mysubset = allIndPars.melt %>% filter(parameter == mypar)
  model = lmer(value ~ context + context_order + (1|subjID), data = mysubset )
  allIndPars.melt$value.corr[allIndPars.melt$parameter == mypar] =  predict(model,
                                                                            mysubset %>% 
                                                                            mutate(context_order = 0)) + resid(model)
  plot(value.corr ~ value, allIndPars.melt %>% filter(parameter == mypar) )
}


allIndPars.diff = merge(subset(allIndPars.melt, context == 'c1'), subset(allIndPars.melt, context == 'c2'), by = c('subjID', 'parameter'), suffixes = c('.c1', '.c2')) %>% mutate(value.corr = value.corr.c2 - value.corr.c1, c1_first = context_order.c1 == 1)
myplot = ggplot(allIndPars.diff, aes(x=0, y = value, fill = c1_first )) + geom_violin() + facet_wrap( . ~ parameter, scales = "free" )
#print(myplot)
myplot = ggplot(allIndPars.diff, aes(x=0, y = value)) + geom_violin() + geom_point(position = "jitter") + facet_wrap( . ~ parameter, scales = "free" )
#print(myplot)

allIndPars.sum <- summarySE(allIndPars.melt, measurevar="value.corr", groupvars=c("Context","parameter_label"))

# Standard error of the mean

myplot.differences = ggplot(allIndPars.sum, aes(x=Context, y=value.corr, ymin = value.corr-se, ymax = value.corr+se)) + 
    geom_point() + 
    geom_errorbar(width=.1) +
    ylab('Parameter value') + 
    xlab('Volatility') + 
    facet_wrap(.~ parameter_label, scales = 'free', nrow = 1)
print(myplot.differences)

myplot.differences.all = ggplot() + 
    geom_line(data = allIndPars.melt, aes(x = Context, y = value, group = subjID), col = "gray", size = 0.5) + 
    geom_point(data = allIndPars.melt, aes(x = Context, y = value, group = subjID), col = "gray") +
    geom_line(data = allIndPars.sum, aes(x=Context, y=value.corr)) + 
    geom_point(data = allIndPars.sum, aes(x=Context, y=value.corr)) + 
    geom_errorbar(data = allIndPars.sum, aes(ymin = value.corr-se, ymax = value.corr+se, x=Context, y=value.corr), width=.1) +
    ylab('Parameter value') + 
    xlab('') + 
    facet_wrap(.~ parameter_label, scales = 'free', nrow = 1)
print(myplot.differences.all)

allIndPars.sum <- summarySE(allIndPars.diff, measurevar="value.corr", groupvars=c( "parameter"))

# Standard error of the mean
ggplot(allIndPars.sum, aes(x=parameter, y=value.corr)) + 
    geom_errorbar(aes(ymin = value.corr-se, ymax = value.corr+se), width=.1) +
    geom_line() +
    geom_point() + 
    ylab('Parameter difference (low volatility - high volatility)') + 
    geom_hline(yintercept = 0, col = 'red')


```

## Check correlation between parameters

```{r, fig.width = 15}

options(width = 300)

xx = allIndPars %>% filter(subjID %in% include_subjects)
cor(xx[mypars])
pairs(xx[mypars])

xx = allIndPars %>% filter(subjID %in% include_subjects & nondectime.p < 2)
cor(xx[mypars])
pairs(xx[mypars])

```



```{r}

HEIGHT1ROW = 4.06
WIDTH1COL = 3.8 
DPI = 600

FIGS_DIR = '../figs'

fig.a1 = ggarrange(myplot.RT, myplot.RT.choice, myplot.choiceprob, ncol=3, nrow=1, labels = c('A', 'B', 'C'))
fig.a2 = ggarrange(myplot.reliab, myplot.differences, ncol=1, nrow=2, labels = c('D', 'E'))
fig.a = ggarrange(fig.a1, fig.a2, ncol=1, nrow=2, heights = c(1, 2))
ggsave(filename=file.path(FIGS_DIR, "Choices.png"), plot = fig.a, dpi = DPI, width = WIDTH1COL*3, height = HEIGHT1ROW*3)


fig.b = ggarrange(myplot.range, ncol=1, nrow=1, labels = c('A'))
ggsave(filename=file.path(FIGS_DIR, "Ratings.png"), plot = fig.a, dpi = DPI, width = WIDTH1COL, height = HEIGHT1ROW)


```




