
## Extract parameters

```{r}
# posterior predictive checks
rm(list = ls())
library(runjags)
library(rjags)
library(MCMCvis)
library(coda)
source('./funcs.R')
WD = '~/Software/EC-DD-Task/data'
WDD = file.path(WD, 'all')

N_samples = 1000

#pars = c("b.drift.delay.mu", "b.drift.amount.mu", "b.drift.delay.pr", "b.drift.amount.pr", 
#            "nondectime.mu", "nondectime.pr", 
#            "noise.mu","noise.pr", 
#            "bias.mu", "bias.kappa", 
#            "gamma.mu", "gamma.pr", 
#            "deviance" )

pars = c(#"e.sG", "e.rG", 
         "b.drift.intercept.mu", "b.drift.amount.mu", 
         "b.drift.intercept.pr", "b.drift.amount.pr", 
         "nondectime.mu", "nondectime.pr", 
         "noise.mu","noise.pr", 
#         "w.mu", "w.kappa",
#         "normk.mu", "normk.pr",
         "bias.mu", "bias.kappa", 
         "deviance" )

check_model = function(myfit, myfit_rjags, myfit_samples) {
  
myfit.MCMCsummary = MCMCsummary(myfit_samples, round = 2)

rhat = myfit.MCMCsummary$Rhat 
n.eff = myfit.MCMCsummary$n.eff

# myfit.MCMCpstr =MCMCpstr(myfit_rjags, func = mean,
#          type = 'summary')

MCMCtrace(myfit_samples, 
        params = pars,
        ISB = FALSE,
        pdf = FALSE)

MCMCplot(myfit_samples, 
         params = pars[-length(pars)] ,
         ref_ovl = TRUE)

MCMCplot(myfit_samples, 
         params = 'b.drift.intercept.p',
         ref_ovl = TRUE)

MCMCplot(myfit_samples, 
         params = 'b.drift.amount.p',
         ref_ovl = TRUE)

# 
# MCMCplot(myfit_samples, 
#          params = 'drift.pr.p',
#          ref_ovl = TRUE)
# 
MCMCplot(myfit_samples,
      params = 'k.p',
      ref_ovl = TRUE)
# MCMCplot(myfit_samples, 
#          params = 'w.p',
#          ref_ovl = TRUE)

print(sort(rhat, decreasing = T)[1:20])
  
#dic.fit = dic.samples(as.jags(myfit)) #
#dic.fit = runjags::extract(myfit, what = "dic", force.resample = T)
#  loo.fit = loo(myfit)
#  waic.fit = 0 # waic(myfit)
#  ics = c(loo.fit, waic.fit)
#  names(ics) = c('loo', 'waic')
#  return(ics)
}
```


```{r, fig.width = 20}
# Load previous fits
load('results/value_diff_simple_ddm-  15-07-2021_04:28-10000-3e+05.RData') #06-07-2021_05:02-10000-3e+05.RData')
#load('results/value_diff_simple_ddm-15-07-2021_02:08-10000-2e+05.RData') 
#load('results/dd_hyperbolic_simple_ddm-15-07-2021_06:55-10000-3e+05.RData')
#load('results/dd_hyperbolic_simple_ddm-15-07-2021_06:55-10000-3e+05.RData')
#load('results/dd_hyperbolic_simple_ddm-15-07-2021_07:56-10000-3e+05-calibrate.RData')
#load('results/dd_hyperbolic_calibration_ddm-16-07-2021_16:10-10000-3e+05-calibrate.RData')

chain1 = as.matrix(coda_samples[[1]])
chain2 = as.matrix(coda_samples[[2]])
chain3 = as.matrix(coda_samples[[3]])
chain4 = as.matrix(coda_samples[[4]])
chain = rbind(chain1, chain2, chain3, chain4)
nsamp = nrow(chain1)

chaincolor = c(rep('red', nsamp), rep('blue', nsamp), rep('green', nsamp), rep('yellow', nsamp))
#plot(chain[, 'gamma.mu'], chain[, 'b.drift.amount.pr'], col = chaincolor, cex = 0.1, pch = 20)

#pars = monitor[ c(grep('\\.mu', monitor), grep('\\.pr$', monitor), grep('\\.kappa', monitor))] 
pairs(chain[, pars[-c(length(pars))] ], col = chaincolor, pch = 20, cex = 0.1)
cc = cor(chain[, pars[-c(length(pars))] ])
View(cc)
#pairs(chain[, pars] , col = chaincolor, pch = 20, cex = 0.1)


ics.value = check_model(myfit, myfit_rjags, myfit_samples)
#ics.linear = check_model(myfit, myfit_rjags, myfit_samples)
#ics.nl = check_model(myfit.nl)
#ics.nl2 = check_model(myfit.nl2)

#print(ics.linear$loo)

```
