
## Extract parameters

```{r}
# posterior predictive checks
rm(list = ls())
library(rstan)
library(loo)
source("./analysis_funcs.R")
WD = '~/Software/EC-DD-Task/data'
N_samples = 1000
check_model = function(myfit) {
  print(traceplot(myfit, pars = c("mu_p", "sigma_p", "mu_slope_p", "sigma_slope_p"), inc_warmup = T))
  print(traceplot(myfit, pars = c("mu_p", "sigma_p", "mu_slope_p", "sigma_slope_p"), inc_warmup = F))
  print(pairs(myfit, pars = c("mu_p", "sigma_p")))
  print(pairs(myfit, pars = c("mu_p", "sigma_p", "mu_slope_p", "sigma_slope_p")))
  print(plot(myfit, pars = c("mu_p", "mu_slope_p")))
#  print(plot(myfit, pars = c("w")))
#  print(plot(myfit, pars = c("k")))
  print(plot(myfit, pars = c("drift_intercept_gen")))
  print(plot(myfit, pars = c("drift_slope_gen")))
 # print(plot(myfit, pars = c("bias_gen")))
  print(plot(myfit, pars = c("nondectime_gen")))
  print(plot(myfit, pars = c("boundary_gen")))
  samples = extract(myfit)
  cc = cor(cbind(samples$mu_p, samples$sigma_p, samples$mu_slope_p, samples$sigma_slope_p))
  print(cc)
  rhat = summary(myfit)$summary[, "Rhat"]
  n_eff = summary(myfit)$summary[, "n_eff"]
  print(sort(rhat[1:10], decreasing = T))
  print(sort(n_eff[1:10]))
  loo.fit = loo(myfit)
  waic.fit = 0 # waic(myfit)
  ics = c(loo.fit, waic.fit)
  names(ics) = c('loo', 'waic')
  print(range(rhat))
  return(ics)
}
```


```{r fig.width = 15}
# Load previous fits

#load('results/linear_drift_ddm29-08-2021_03:58-10000-stan.RData')
load('results/linear_drift_ddm03-09-2021_06:02-11000-stan.RData')

myfit.linear = myfit

ics.linear = check_model(myfit.linear)

#print(ics.linear$loo)
#print(ics.nl$loo )

```

```{r}
#samples = extract(myfit)
#k = samples$k
#mu_p = samples$mu_p
#plot(rowMeans(k),  mu_p[, 5]) 
```

